#!/bin/bash

fake_path='path1:path2:path3'

poly () {
  echo "$1" ' ' "$2"
  result=$(($1*$1*$1+$2*$2+$1*$2))
  echo 'The result is' "$result"
}

if [ ! "$1" ] || [ "$2" ]; then
  echo 'Only 1 argument allowed'
  exit 1
fi

if [ "$1" ]; then
  if [ ! -d "$1" ] || [ -L "$1" ]; then
    echo 'Argument is not a valid directory'
    exit 1
  fi
  directory="$1"
fi

echo 'directory is' "$directory"

path2=`echo $fake_path | tr ":" " "`
# OR: path2=${fake_path//:/ }
echo "$path2"
in_path=0
for a_path in $path2
do
  echo "$a_path"
  if [ $a_path = $directory ]; then
     echo 'match found'
     in_path=1
  fi
done

if [ "$in_path" == 0 ]; then
  echo 'match NOT found'
  fake_path+=:"$directory"
fi

file=`ls -prt | grep -v / | head -n 1`
x=${#file}
# y=0
# all_files=`ls`
# for a_file in $all_files
# do
#  if [ ${#a_file} -eq 2 ]; then
#    y=$((y+1))
#  fi
#done

#alternative method, one-liner
y=`ls | awk 'length == 2' | wc -l`

poly "$x" "$y"

echo 'fake path is' "$fake_path"