#!/bin/bash

echo 'TEST 1'
echo -e '1\n2\n3' | python3 shuf.py
echo 'Exit code:' $?
echo 'TEST 2'
python3 shuf.py -i 10-20
echo 'Exit code:' $?

echo 'TEST 3'
python3 shuf.py -i 10-20 -n 5
echo 'Exit code:' $?

echo 'TEST 4'
python3 shuf.py -i 10-20 -n 15
echo 'Exit code:' $?

echo 'TEST 5'
python3 shuf.py -i
echo 'Exit code:' $?

echo 'TEST 6'
python3 shuf.py -i 2-0
echo 'Exit code:' $?

echo 'TEST 7'
python3 shuf.py -i 2-2
echo 'Exit code:' $?

echo 'TEST 8'
python3 shuf.py -i 3-2
echo 'Exit code:' $?

echo 'TEST 9'
python3 shuf.py correct13.txt -n 5
echo 'Exit code:' $?

echo 'TEST 10'
python3 shuf.py correct13.txt -n 0
echo 'Exit code:' $?

echo 'TEST 11'
python3 shuf.py correct13.txt -n 3jklj
echo 'Exit code:' $?

echo 'TEST 12'
python3 shuf.py correct13.txt -i 2-4 -n 2
echo 'Exit code:' $?

echo 'TEST 13'
python3 shuf.py correct13.txt -n -1
echo 'Exit code:' $?

echo 'TEST 14'
python3 shuf.py correct13.txt -n 5 -r
echo 'Exit code:' $?

echo 'TEST 15'
python3 shuf.py correct13.txt -n -1 -r
echo 'Exit code:' $?

echo 'TEST 16'
python3 shuf.py correct13.txt --input-range 10-15
echo 'Exit code:' $?

echo 'TEST 17'
python3 shuf.py correct13.txt --head-count 2
echo 'Exit code:' $?

echo 'TEST 18'
python3 shuf.py --head-count 2 correct13.txt
echo 'Exit code:' $?

echo 'TEST 19'
python3 shuf.py --repeat --head-count 4 correct13.txt
echo 'Exit code:' $?

echo 'TEST 20'
echo -e 'a\nb\nc\ndd' | python3 shuf.py -
echo 'Exit code:' $?

echo 'TEST 21'
echo -e 'a\nb\nc\ndd' | python3 shuf.py - -n 5
echo 'Exit code:' $?

echo 'TEST 22'
echo -e 'a\nb\nc\ndd' | python3 shuf.py - -i 1-10
echo 'Exit code:' $?

echo 'TEST 23'
python3 shuf.py nonexistent.txt
echo 'Exit code:' $?

echo 'TEST 24'
python3 shuf.py -n 8 nonexistent.txt
echo 'Exit code:' $?

# echo 'TEST 19'
# echo 'TEST 19'

# echo 'TEST 19'
# echo 'TEST 19'
# echo 'TEST 19'


